' Gambas module file

'
' Gambas extra functions
' Armazón para contruir pogramas.
'
' Copyright (C) Martín Belmonte
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 2 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, write to the Free Software
' Foundation, Inc., 51 Franklin St, Fifth Floor,
' Boston, MA  02110-1301  USA
'

'Componentes necesarios: gb.sdl2.audio

Public Function PlaySound(strPath As String) As String ''Esta funcion reproduce un archivo OGG comn el programa mplayer. Dependenciaas: mplayer. Devuelve el numero PID del proceso.

  If Exist(strPath) = True Then
    Music.Load(strPath)
    Music.Play()
  Endif
  While Music.Playing
    Wait 0.2
  Wend
  Return strPath

End