' Gambas module file

'
' Gambas extra functions
' Coleccion de 93 funciones desarrolladas en la comunidad gambas.
'
' Copyright (C) Martín Belmonte y otros
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 2 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, write to the Free Software
' Foundation, Inc., 51 Franklin St, Fifth Floor,
' Boston, MA  02110-1301  USA
'

'## variables de GEF ## Son las variables basicas del "framework" GEF

Public stxProgKey As New String[] ''Clave de los parametros del programa
Public stxProgVal As New String[] ''<ul><li>0 Database Engine</li><li>1 Database Host</li><li>2 Database Name</li><li>3 Database Port</li><li>4 Database user</li><li>5 Database password</li><li>6 Report 1</li><li>7 Report 2</li><li>8 Report 3</li><li>9 Report 4</li><li>10 Report 5</li><li>...</li><li>18 Mensajes centralizados]</li></ul>
Public strAppPath As String
Public strDBName As String
Public stxDBEngines As New String[] ''Motores de bases de datos soportadas por gambas
Public stxPackages As New String[]
Public conProgram As New Connection ''Conexión a la base de datos
Public strTemplate As String  ''Plantilla de la base de datos
Public stxTables As New String[] ''Lista de tablas

Public stxTableFields As New String[][] ''Lista de campos de las tablas

Public stxViews As New String[] ''Lista de vistas
Public stxVTitles As New String[][] ' Lista de vistas mejorada con titulos "humanos" e iconos
Public stxViewFields As New String[][] ''Lista de campos de las vistas
Public stxFTitles As New String[][] ''Lista de títulos de los campos de las vistas y de las tablas
Public stxHeaders As New String[] ''<ul><li>0 Acronimo de dos letras "es"</li><li>1 Acronimo de tres letras "spa"</li><li>2 Nombre en inglés "Spanish"</li><li>3 Nombre nativo "Español"</li><li>4 Grupo del idioma "Indo-European"</li><li>5 Alfabeto "Latn" (latino)</li><li>6 Traducir [True/False]</li></ul>
Public stxFieldsTableCurrent As New String[] ''lista de campos para crear los botones de filtros
Public stxFieldsViewCurrent As New String[] ''lista de campos para crear los botones de filtros
Public resProgram As Result
' Variables para el treeview de Datos
Public strViewNameSqlCurrent As String
Public strViewNameHumanCurrent As String
Public strSQLCurrent As String
' Public intDataTreeWidth As Integer
' Public intDataTreeHeight As Integer
' Public intDataGridWidth As Integer
' Public intDataGridHeight As Integer

'Public strInputLanguage As String

'## variables del Programa ##
'
'
'////////////////////////////

Public Sub Main()

  Dim strSQL As String
  Dim resSQL As Result
  Dim intTable As Integer
  Dim intView As Integer
  Dim strTableTmp As String
  Dim strViewTmp As String
  Dim stxTmp As New Variant[][]
  Dim intTmp As Integer
  Dim intP As Integer
  Dim intKey As Integer

  strAppPath = User.Home &/ "." & Application.Name
  stxDBEngines = GEFUtility.FileLoad("engines.txt") ' Motores de bases de datos soportados por gambas

  ' Existencia de directorio de la aplicacion en el directorio home. Esto se ejecutara una unica vez.
  ' Aqui se pueden agregar mas comprobaciones de este tipo para copia de archivos de configuracion y demas cosas similares
  If Exist(strAppPath) = False Then
    Mkdir strAppPath
  Endif
  Wait 0.05
  If Exist(strAppPath &/ "README.md") = False Then
    Copy "README.md" To strAppPath &/ "README.md"
  Endif
  If Exist(strAppPath &/ "logo.png") = False Then
    Copy "logo.png" To strAppPath &/ "logo.png"
  Endif

  ' Carga de los parametros del prgrama conjuntamente con gb.settings./////////////////////////
  strDBName = Replace(Application.Name & ".db", "-", "")

  If Initiator() = 1 Then
    strTemplate = GEFDataEdit.DBTemplate(stxProgVal)
    If strTemplate <> "" Then
      Print strTemplate
      File.Save(User.Home &/ stxProgVal[2] & ".template", strTemplate)
    Endif
    For intKey = 0 To stxProgKey.Max
      stxProgVal[intKey] = Settings[stxProgKey[intKey], stxProgVal[intKey]]
    Next
  Endif

  Select stxProgVal[7]
    Case "T", "True"
      Select Dependences() ' Estado de las dependencias.////////////////////////////////////////////////
        Case 0
          Message.Info("Algunas caracteristicas no funcionaran hasta que no instale las dependencias")
        Case 1
      End Select
  End Select

  ' Existencia de la base de datos.////////////////////////////////////////////////////
  ' Se pasan los datos de la conexion y segun exista la base o no se procedera a crear y conectar o a conectar

  conProgram.Type = stxProgVal[0]
  conProgram.Host = stxProgVal[1]
  conProgram.Name = stxProgVal[2]
  conProgram.Port = stxProgVal[3]
  conProgram.User = stxProgVal[4]
  conProgram.Password = stxProgVal[5]

  conProgram = GEFData.DBOpen(stxProgVal)

  stxVTitles = GEFData.DBViewsTitles()
  stxFTitles = GEFData.DBFieldsTitles()

  If stxVTitles.Count > 0 Then
    'LoadTitles() = 1 Then
    If stxFTitles.Count > 0 Then

      stxTables.Clear
      stxTables.Insert(GEFData.getTables(conProgram, "table")) ' Lista de TABLAS

      stxTableFields.Clear
      For intTable = 0 To stxTables.Max
        strTableTmp = stxTables[intTable]
        strSQL = "select * from " & strTableTmp
        resSQL = conProgram.Exec(strSQL)

        stxTmp.Clear
        stxTmp.Insert(GEFData.getFields(conProgram, strTableTmp, "table", stxFTitles))

        For intTmp = 0 To stxTmp.Max
          stxTableFields.Add(stxTmp[intTmp])
        Next
      Next
      Print "###Tablas###"
      For intP = 0 To stxTableFields.Max
        Print stxTableFields[intP].Join(":")
      Next

      stxViews.Clear
      stxViews.Insert(GEFData.getTables(conProgram, "view")) ' Lista de VISTAS

      For intView = 0 To stxViews.Max
        strViewTmp = stxViews[intView]
        strSQL = "select * from " & strViewTmp
        resSQL = conProgram.Exec(strSQL)
        stxViewFields.Insert(GEFData.getFields(conProgram, strViewTmp, "view", stxFTitles))
      Next
      Print "###Vistas ###"
      For intP = 0 To stxViewFields.Max
        Print stxViewFields[intP].Join(":")
      Next

      If conProgram.Opened Then
        FMain.Show()
      Else
        Message.Warning(("No se pudo abrir la conexión a la base de datos") &
          "\n" & ("Por favor verifique la configuración"))
        FMain.Show()
      Endif
    Endif
  Endif

End

' Private Sub LoadViews()
'
'   stxViews.Clear
'   stxViews.Insert(GEFDataEdit.getTables(conProgram, "view")) ' Lista de VISTAS
'
' End

' Private Function LoadTitles() As String ''La carga de títulos de los campos de las tablas y de las vistas. De esta manera permite luego traducir la aplicacion mas facilmente. La funcion trabaja con tres parametros, el nombre de la tabla o vista el nombre del campo, y el título de este campo, que sera el que se traducira. Esta funcion permite controlar en un solo sitio todos los titulos.
'
'   ' // Carga de vistas // Modificar cuando se use otra estructura de BBDD
'   stxFTitles.Add(["view_jobs", "jidx", ("Índice")])
'   stxFTitles.Add(["view_jobs", "jname", ("Trabajo")])
'   stxFTitles.Add(["view_jobs", "jdate", ("Fecha")])
'   stxFTitles.Add(["view_jobs", "jowner", ("Cliente")])
'
'   stxFTitles.Add(["boms", "midx", ("Índice")])
'   stxFTitles.Add(["boms", "mjob", ("Trabajo")])
'   stxFTitles.Add(["boms", "mcod", ("Código")])
'   stxFTitles.Add(["boms", "mqty", ("Cantidad")])
'
'   stxFTitles.Add(["view_boms", "midx", ("Índice")])
'   stxFTitles.Add(["view_boms", "mjob", ("Trabajo")])
'   stxFTitles.Add(["view_boms", "mcod", ("Código")])
'   stxFTitles.Add(["view_boms", "mclass", ("Clase")])
'   stxFTitles.Add(["view_boms", "mqty", ("Cantidad")])
'   stxFTitles.Add(["view_boms", "mprice", ("Precio")])
'   stxFTitles.Add(["view_boms", "muom", ("Unidad")])
'   stxFTitles.Add(["view_boms", "msupplier", ("Suministrador")])
'
'   stxFTitles.Add(["codcls", "sidx", ("Índice")])
'   stxFTitles.Add(["codcls", "sname", ("Clase")])
'
'   stxFTitles.Add(["codes", "cidx", ("Índice")])
'   stxFTitles.Add(["codes", "cname", ("Insumo")])
'   stxFTitles.Add(["codes", "cclass", ("Clase")])
'   stxFTitles.Add(["codes", "cqty", ("Cantidad")])
'   stxFTitles.Add(["codes", "cuom", ("Unidad")])
'   stxFTitles.Add(["codes", "cprice", ("Precio")])
'
'   stxFTitles.Add(["view_codes", "cidx", ("Índice")])
'   stxFTitles.Add(["view_codes", "cname", ("Insumo")])
'   stxFTitles.Add(["view_codes", "cclass", ("Clase")])
'   stxFTitles.Add(["view_codes", "cqty", ("Cantidad")])
'   stxFTitles.Add(["view_codes", "cuom", ("Unidad")])
'   stxFTitles.Add(["view_codes", "cprice", ("Precio")])
'
'   stxFTitles.Add(["composites", "aidx", ("Índice")])
'   stxFTitles.Add(["composites", "aname", ("Compuesto")])
'   stxFTitles.Add(["composites", "adesc", ("Descripción")])
'
'   stxFTitles.Add(["deliverables", "didx", ("Índice")])
'   stxFTitles.Add(["deliverables", "dname", ("Informe")])
'
'   stxFTitles.Add(["jobs", "jidx", ("Índice")])
'   stxFTitles.Add(["jobs", "jname", ("Trabajo")])
'   stxFTitles.Add(["jobs", "jdate", ("Fecha")])
'   stxFTitles.Add(["jobs", "jowner", ("Cliente")])
'   stxFTitles.Add(["jobs", "jlogistic", ("Logística")])
'
'   stxFTitles.Add(["logistics", "lidx", ("Índice")])
'   stxFTitles.Add(["logistics", "lname", ("Logística")])
'
'   stxFTitles.Add(["owners", "oidx", ("Índice")])
'   stxFTitles.Add(["owners", "oname", ("Cliente")])
'
'   stxFTitles.Add(["suppliers", "fidx", ("Índice")])
'   stxFTitles.Add(["suppliers", "fname", ("Suministrador")])
'
'   stxFTitles.Add(["uoms", "uidx", ("Índice")])
'   stxFTitles.Add(["uoms", "uname", ("Simbolo")])
'   stxFTitles.Add(["uoms", "udesc", ("Unidad")])
'
'   ' Nombres de tablas y vistas
'   stxVTitles.Add(["view_jobs", ("Trabajos"), "icon:/16/add"])
'   stxVTitles.Add(["view_boms", ("Materiales y tareas"), "icon:/16/add"])
'   stxVTitles.Add(["view_codes", ("Códigos"), "icon:/16/add"])
'   stxVTitles.Add(["view_composites", ("Compuestos"), "icon:/16/delete"])
'   stxVTitles.Add(["view_deliverables", ("Informes"), "icon:/16/delete"])
'   stxVTitles.Add(["view_logistic", ("Logística"), "icon:/16/delete"])
'   stxVTitles.Add(["view_owners", ("Clientes"), "icon:/16/delete"])
'   stxVTitles.Add(["view_suppliers", ("Suministradores"), "icon:/16/delete"])
'   stxVTitles.Add(["view_uoms", ("Unidades de medida"), "icon:/16/delete"])
'
'   If stxVTitles.Count > 0 Then
'     Return 1
'   Else
'     Return 0
'   Endif
'
' End

Public Function Initiator() As Integer  ''Funcion que carga los parametros por defecto del programa. 1 ok, 0 Matrices iguales pero no se cargo todo -1 matrices distintas

  stxProgKey = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
  stxProgVal = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]

  stxProgKey[0] = "Program/Database-Engine"
  stxProgVal[0] = Settings[stxProgKey[0], "sqlite3"]

  stxProgKey[1] = "Program/Database-Host"
  stxProgVal[1] = Settings[stxProgKey[1], strAppPath]

  stxProgKey[2] = "Program/Database-Name"
  stxProgVal[2] = Settings[stxProgKey[2], strDBName]

  stxProgKey[3] = "Program/Database-Port"
  stxProgVal[3] = Settings[stxProgKey[3], ""]

  stxProgKey[4] = "Program/Database-User"
  stxProgVal[4] = Settings[stxProgKey[4], User.Name]

  stxProgKey[5] = "Program/Database-Password"
  stxProgVal[5] = Settings[stxProgKey[5], ""]

  stxProgKey[6] = "Program/File-Log"
  stxProgVal[6] = Settings[stxProgKey[6], strAppPath &/ strDBName & ".log"]

  stxProgKey[7] = "Program/Check-Dependences-on-startup"
  Select Settings[stxProgKey[7], ""]
    Case "T", "True"
      stxProgVal[7] = "True"
    Case Else
      stxProgVal[7] = ""
  End Select

  stxProgKey[8] = "Program/Code-empty-lines"
  Select Settings[stxProgKey[8], ""]
    Case "T", "True"
      stxProgVal[8] = "True"
    Case Else
      stxProgVal[8] = ""
  End Select

  ' Desde donde se esta ejecutando la aplicación
  stxProgKey[9] = "Program/Running-From"
  Select GEFUtility.WhereRun()
    Case 0
      stxProgVal[9] = "gambas"
    Case 1
      stxProgVal[9] = "ide"
    Case Else
      stxProgVal[9] = ""
  End Select

  stxProgKey[10] = "Program/Report-1"
  stxProgVal[10] = Settings[stxProgKey[10], "pandoc"]
  stxProgKey[11] = "Program/Report-2"
  stxProgVal[11] = Settings[stxProgKey[11], "pandoc"]
  stxProgKey[12] = "Program/Report-3"
  stxProgVal[12] = Settings[stxProgKey[12], "pandoc"]
  stxProgKey[13] = "Program/Report-4"
  stxProgVal[13] = Settings[stxProgKey[13], "pandoc"]
  stxProgKey[14] = "Program/Report-5"
  stxProgVal[14] = Settings[stxProgKey[14], "pandoc"]
  stxProgKey[15] = "Program/Editor-Theme"
  stxProgVal[15] = Settings[stxProgKey[15], "gef"]
  stxProgKey[16] = "Program/Show-GEF"
  stxProgVal[16] = Settings[stxProgKey[16], ""]
  stxProgKey[17] = "Program/Altern-App-Name"
  stxProgVal[17] = Settings[stxProgKey[17], ""]
  stxProgKey[18] = "Program/Key-18"
  stxProgVal[18] = Settings[stxProgKey[18], ""]
  stxProgKey[19] = "Program/Key-19"
  stxProgVal[19] = Settings[stxProgKey[19], ""]

  ' Ventana del formulario principal
  stxProgKey[20] = "Program/Tree-Width"
  stxProgVal[20] = Settings[stxProgKey[20], 150]
  stxProgKey[21] = "Program/Tree-Height"
  stxProgVal[21] = Settings[stxProgKey[21], 150]
  stxProgKey[22] = "Program/Grid-Width"
  stxProgVal[22] = Settings[stxProgKey[22], 300]
  stxProgKey[23] = "Program/Grid-Height"
  stxProgVal[23] = Settings[stxProgKey[23], 150]
  stxProgKey[24] = "Program/Key-24"
  stxProgVal[24] = Settings[stxProgKey[24], ""]
  stxProgKey[25] = "Program/Key-25"
  stxProgVal[25] = Settings[stxProgKey[25], ""]
  stxProgKey[26] = "Program/Key-26"
  stxProgVal[26] = Settings[stxProgKey[26], ""]
  stxProgKey[27] = "Program/Key-27"
  stxProgVal[27] = Settings[stxProgKey[27], ""]
  stxProgKey[28] = "Program/Key-28"
  stxProgVal[28] = Settings[stxProgKey[28], ""]
  stxProgKey[29] = "Program/Key-29"
  stxProgVal[29] = Settings[stxProgKey[29], ""]
  stxProgKey[30] = "Program/Key-30"
  stxProgVal[30] = Settings[stxProgKey[30], ""]
  stxProgKey[31] = "Program/Key-31"
  stxProgVal[31] = Settings[stxProgKey[31], ""]
  stxProgKey[32] = "Program/Key-32"
  stxProgVal[32] = Settings[stxProgKey[32], ""]
  stxProgKey[33] = "Program/Key-33"
  stxProgVal[33] = Settings[stxProgKey[33], ""]
  stxProgKey[34] = "Program/Key-34"
  stxProgVal[34] = Settings[stxProgKey[34], ""]

  If stxProgKey.Max = stxProgVal.Max Then
    If stxProgKey.Max = 18 Then
      Return 1
    Else
      Return 0
    Endif
  Else
    Return -1
  Endif

End

Public Function Dependences() As Integer ''Analisis de dependencias, si hay paquetes que falta instalar se procede a instalarlos y la funcion retorna la cantidad remanente de paquetes, siendo cero si se instalaron todos.

  Dim stxDep As New String[]
  Dim stxInstall As New String[]
  Dim str As String
  Dim strCmm As String

  str &= ("Debes instalar los siguientes paquetes") & ":\n"

  Select GEFSys.DistroShort()

    Case "debian", "ubuntu", "mint"
      strCmm = "sudo apt-get install "
      If Exist("deb.txt") = True Then
        stxPackages = GEFUtility.FileLoad("deb.txt")
      Endif
    Case "manjaro", "arch"
      strCmm = "sudo pacman -S "
      If Exist("arc.txt") = True Then
        stxPackages = GEFUtility.FileLoad("arc.txt")
      Else
        If Exist("deb.txt") = True Then
          stxPackages = GEFUtility.FileLoad("deb.txt")
        Endif
      Endif
    Case "fedora", "redhat"
      strCmm = "sudo dnf install "
      If Exist("rht.txt") = True Then
        stxPackages = GEFUtility.FileLoad("rht.txt")
      Else
        If Exist("deb.txt") = True Then
          stxPackages = GEFUtility.FileLoad("deb.txt")
        Endif
      Endif

    Case "gentoo"
      strCmm = "sudo emerge -a "
      If Exist("gto.txt") = True Then
        stxPackages = GEFUtility.FileLoad("gto.txt")
      Else
        If Exist("deb.txt") = True Then
          stxPackages = GEFUtility.FileLoad("deb.txt")
        Endif
      Endif

    Case "suse", "opensuse"
      strCmm = "sudo zipper install "
      If Exist("osu.txt") = True Then
        stxPackages = GEFUtility.FileLoad("osu.txt")
      Else
        If Exist("deb.txt") = True Then
          stxPackages = GEFUtility.FileLoad("deb.txt")
        Endif
      Endif

  End Select

  If stxPackages.Count > 0 Then
    stxPackages = GEFSys.PkgDep(stxPackages)
    If stxPackages.Count > 0 Then ' Existen paquete que no estan instalados

      File.Save("/tmp/apt.txt", str & strCmm & stxPackages.Join(" "))
      Wait 1
      Desktop.Open("/tmp/apt.txt")

      ' stxPackages = GEFSys.PkgInstall(stxPackages)
      '
      ' If stxPackages.Count > 0 Then
      '   Message.Info("Algunos paquetes no se pudieron instalar.")
      ' Else
      '   GEFUtility.FileLog("Todos los paquetes fueron instalados.")
      ' Endif

    Endif
  Endif
  Return stxPackages.Count

End

Public Function Terminator() As Integer ''Funcion que guarda las configuraciones que se modificaron en el programa antes de cerrarlo.

  Dim int As Integer
  ' Guardando los parametros del programa
  For int = 0 To stxProgKey.Max
    Settings[stxProgKey[int]] = stxProgVal[int]
    Print "Guardando: " & stxProgKey[int] & ": " & stxProgVal[int]
  Next

  ' Guardando los parametros de la grilla
  For int = 0 To stxViewFields.Max

    Settings[stxViewFields[int][0] & "-Order" &/ stxViewFields[int][1]] = stxViewFields[int][3]
    Settings[stxViewFields[int][0] & "-FilterType" &/ stxViewFields[int][1]] = stxViewFields[int][4]
    Settings[stxViewFields[int][0] & "-FilterValue" &/ stxViewFields[int][1]] = stxViewFields[int][5]

    Select stxViewFields[int][6]
      Case "", "75"
        Settings[stxViewFields[int][0] & "-Width" &/ stxViewFields[int][1]] = ""
      Case Else
        Settings[stxViewFields[int][0] & "-Width" &/ stxViewFields[int][1]] = stxViewFields[int][6]
    End Select
  Next
  ' Guardando las proporciones y dimensiones del formulario

  Settings["Program/Tree-Width"] = GEFStarter.stxProgVal[20] 'GEFStarter.intDataTreeWidth
  Settings["Program/Tree-Height"] = GEFStarter.stxProgVal[21] 'GEFStarter.intDataTreeHeight

  Settings["Program/Grid-Width"] = GEFStarter.stxProgVal[22] 'GEFStarter.intDataGridWidth
  Settings["Program/Grid-Height"] = GEFStarter.stxProgVal[23] 'GEFStarter.intDataGridHeight

  Settings.Save

  Return 1

End
