' Gambas module file

'
' Gambas extra functions
' Armazón para contruir pogramas.
'
' Copyright (C) Martín Belmonte
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 2 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, write to the Free Software
' Foundation, Inc., 51 Franklin St, Fifth Floor,
' Boston, MA  02110-1301  USA
'
Public Function ListHtml(strList As String, strSep As String) As String

  Dim stx As New String[]
  Dim str As String
  Dim int As Integer

  If InStr(strList, strSep) > 0 Then
    stx = Split(strList, strSep)
  Else
    If strList <> "" Then
      stx.Add(strList)
    Endif
  Endif

  str = "<ul>"
  For int = 0 To stx.Max
    str &= "<li>" & stx[int] & "</li>"
  Next
  str &= "</ul>"

  Return str

End
